site_name: srai
site_url: null

repo_url: https://github.com/srai-lab/srai
repo_name: srai-lab/srai

edit_uri: ""

watch:
  - examples

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.stick
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - toc.follow
    - content.code.annotate
  favicon: assets/logos/favicon.ico
  logo: assets/logos/srai-logo-symbol.svg
  icon:
    repo: material/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  analytics:
    provider: google
    property: G-VDSV9JTGPD
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-


            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/srai-lab/srai/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      github:
        name: Github
        checked: true
      analytics:
        name: Google Analytics
        checked: true
    actions:
      - accept
      - manage
  version:
    provider: mike

extra_css:
  - assets/css/font.css
  - assets/css/palette.css
  - assets/css/jupyter.css

copyright: >
  Copyright &copy; 2022 - {current_year} SRAI Lab –
  <a href="#__consent">Change cookie settings</a>

plugins:
  - mike:
      canonical_version: "latest"
      version_selector: true
  - gen-files:
      scripts:
        - docs/copy_examples.py
        - docs/generate_api.py
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      ignore_h1_titles: true
      execute: !ENV [MKDOCS_EXECUTE_JUPYTER, false]
      include_source: false
      allow_errors: false
  - mermaid2
  - awesome-pages

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
