name: "Test - DEV"
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: "Run tests job"
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
    # uses: ./.github/workflows/_tests.yml
